### ISSUE TITLE
Do not use "negative" boolean prop names

### ISSUE THREAD

**Issue by ogonkov** [gravity-ui/rfc#11]
## Objective

I suggest to always use "affirmative" name for boolean props, because it looks more clear and shorter, than "negative" names.

## Solution Proposal

Deprecate negative prop names in favor of affirmative names

Example

| Before | After |
| :--- | :--- |
| `disableBodyScrollLock` | `hasBodyScrollLock = true` |
| `disableFocusTrap` | `focusTrap = true` |

## Definition of done

Components use affirmative names for props.

**Comment by SeqviriouM** [comment]
@amje @korvin89 what do you think?

**Comment by korvin89** [comment]
@ogonkov what about all `disabled` properties? :)

**Comment by ogonkov** [comment]
@korvin89 what about them?

`disabled` is shorten version of `isDisabled`

**Comment by korvin89** [comment]
> @korvin89 what about them?
> 
> `disabled` is shorten version of `isDisabled`

Yep. And it is a negative as well

**Comment by amje** [comment]
@ogonkov It should be considered for every component individually, we cannot just rename all `disable*` props. And also it's a personal preference. For instance, I prefer `<Component disableSomeFeature />` instead if `<Component hasSomeFeature={false}`.
