### ISSUE TITLE
Modular assembly of the @gravity-ui/websql-autocomplete package

### ISSUE THREAD

**Issue by itwillwork** [gravity-ui/rfc#14]
## Objective

The `dist/index.js` file from `@gravity-ui/websql-autocomplete` is almost 5.2MB

![telegram-cloud-photo-size-2-5429371350214107918-y](https://github.com/gravity-ui/rfc/assets/15855766/eb556fe2-115e-40e1-86e3-1e3aabc56968)

## Solution Proposal

Assemble the build separately by language (clickhouse, postgresql, mysql и yql).

## Definition of done

The required language can be imported modularly from the `@gravity-ui/websql-autocomplete` package

Ex.
```js
import {parseYqlQuery, YQLLexer, YQLParser} from '@gravity-ui/websql-autocomplete/yql';
```

**Comment by SeqviriouM** [comment]
@roberthovsepyan @Raubzeug what do you think?

**Comment by Raubzeug** [comment]
As for me, separate build should be done 100%.
But I'm not sure we should expose Parser and Lexer directly - it may spawn duplicate logic inside applications. As for me, common goals (autocomplete, syntax colorize) should be achieved inside library, and relevant api should be exposed. Parser and Lexer are low-level entities, they may change dramatically, and I think that user should not be aware of it.
@NikitaShkaruba @roberthovsepyan

**Comment by SeqviriouM** [comment]
@NikitaShkaruba @roberthovsepyan what do you think?

**Comment by roberthovsepyan** [comment]
I agree with @Raubzeug. I don't see why we now need the extra exports of parser, lexer.
The rest is great

**Comment by SeqviriouM** [comment]
@NikitaShkaruba @roberthovsepyan @Raubzeug what are our next steps? Will you be able to do this task, or will we look for a volunteer?

**Comment by roberthovsepyan** [comment]
@SeqviriouM we already implemented this
Closing the issue now

**Comment by roberthovsepyan** [comment]
Implemented in https://github.com/gravity-ui/websql-autocomplete/pull/196
