### ISSUE TITLE
customView prop in date pickers

### ISSUE THREAD

**Issue by St1ggy** [gravity-ui/rfc#17]
I need a RangeDatePicker with a custom trigger. How can I achieve this without a prop for customView?

**Comment by SeqviriouM** [comment]
@amje @ValeraS @korvin89

**Comment by korvin89** [comment]
@St1ggy Hi!

Control in `RangeDatePicker` is the main part of the component and contains a lot of complex logic. This component doesn't have any sense without this valuable part.

You can mix [Button](https://preview.gravity-ui.com/uikit/?path=/docs/components-inputs-button--docs) (or any trigger you want), [Popup](https://preview.gravity-ui.com/uikit/?path=/docs/components-overlays-popup--docs) and [RangeCalendar](https://preview.gravity-ui.com/date-components/?path=/docs/components-rangecalendar--docs) to create component you want.

**Comment by St1ggy** [comment]
> @St1ggy Hi!
> 
> Control in `RangeDatePicker` is the main part of the component and contains a lot of complex logic. This component doesn't have any sense without this valuable part.
> 
> You can mix [Button](https://preview.gravity-ui.com/uikit/?path=/docs/components-inputs-button--docs) (or any trigger you want), [Popup](https://preview.gravity-ui.com/uikit/?path=/docs/components-overlays-popup--docs) and [RangeCalendar](https://preview.gravity-ui.com/date-components/?path=/docs/components-rangecalendar--docs) to create component you want.

But I don’t need RangeCalendar… I need exactly the same RangePicker but with a custom control button

**Comment by korvin89** [comment]
> > @St1ggy Hi!
> > Control in `RangeDatePicker` is the main part of the component and contains a lot of complex logic. This component doesn't have any sense without this valuable part.
> > You can mix [Button](https://preview.gravity-ui.com/uikit/?path=/docs/components-inputs-button--docs) (or any trigger you want), [Popup](https://preview.gravity-ui.com/uikit/?path=/docs/components-overlays-popup--docs) and [RangeCalendar](https://preview.gravity-ui.com/date-components/?path=/docs/components-rangecalendar--docs) to create component you want.
> 
> But I don’t need RangeCalendar… I need exactly the same RangePicker but with a custom control button

As I pointed out earlier, the input for the current component is a fundamental component, the replacement of which is not provided for by the idea of this component. `RangeDatePicker` component is a high level composition of components I described on my previous message.

Will be it okay if we create a story for RangeCalendar for your case?

**Comment by St1ggy** [comment]
> > > @St1ggy Hi!
> > > Control in `RangeDatePicker` is the main part of the component and contains a lot of complex logic. This component doesn't have any sense without this valuable part.
> > > You can mix [Button](https://preview.gravity-ui.com/uikit/?path=/docs/components-inputs-button--docs) (or any trigger you want), [Popup](https://preview.gravity-ui.com/uikit/?path=/docs/components-overlays-popup--docs) and [RangeCalendar](https://preview.gravity-ui.com/date-components/?path=/docs/components-rangecalendar--docs) to create component you want.
> > 
> > 
> > But I don’t need RangeCalendar… I need exactly the same RangePicker but with a custom control button
> 
> As I pointed out earlier, the input for the current component is a fundamental component, the replacement of which is not provided for by the idea of this component. `RangeDatePicker` component is a high level composition of components I described on my previous message.
> 
> Will be it okay if we create a story for RangeCalendar for your case?

I'm not sure if this is possible :)
Here's my case
<img width="315" alt="image" src="https://github.com/user-attachments/assets/aaae6b18-f83e-43cc-b02e-c2eb58edc459">
Both "from" and "to" are optional

**Comment by korvin89** [comment]
You've created issue about [RangeDatePicker](https://preview.gravity-ui.com/date-components/?path=/docs/components-rangedatepicker--docs), but now I got You were talking about [RelativeRangeDatePicker](https://preview.gravity-ui.com/date-components/?path=/docs/components-relativerangedatepicker--docs). They are completely different components.

You can mix [RelativeRangeDatePickerDialog](https://github.com/gravity-ui/date-components/blob/29032a533b9e3a58952cbc68de5b6f205a4edd04/src/components/RelativeRangeDatePicker/index.ts#L2) component with any trigger you want. Is it okay?

**Comment by St1ggy** [comment]
> You've created issue about [RangeDatePicker](https://preview.gravity-ui.com/date-components/?path=/docs/components-rangedatepicker--docs), but now I got You were talking about [RelativeRangeDatePicker](https://preview.gravity-ui.com/date-components/?path=/docs/components-relativerangedatepicker--docs). They are completely different components.
> 
> You can mix [RelativeRangeDatePickerDialog](https://github.com/gravity-ui/date-components/blob/29032a533b9e3a58952cbc68de5b6f205a4edd04/src/components/RelativeRangeDatePicker/index.ts#L2) component with any trigger you want. Is it okay?

Can I disable relative `f(x)` buttons? I don't need them

**Comment by korvin89** [comment]
> Can I disable relative `f(x)` buttons? I don't need them

Nope. This component designed exactly for relative dates handling. If you don't need them, you could check regular [RangeCalendar](https://preview.gravity-ui.com/date-components/?path=/docs/components-rangecalendar--docs), this component more convenient for simple dates range selection

**Comment by SeqviriouM** [comment]
@korvin89 can you describe the current status? Is this issue still relevant or should it be put on hold or closed?

**Comment by korvin89** [comment]
@SeqviriouM 

After the discussion in the telegram, I realized that @St1ggy is required:
- add a custom trigger to open the date selection dialog
- remove the `f(x)` buttons that switch the date input mode

We have a `RelativeRangeDatePicker` component, which was created specifically for advanced work with date range selection and has quite a lot of different settings (the ability to work with relative dates, timezone selection, preset settings etc). This component is a composition of more atomic components and does not involve flexible configuration. If we make it possible to remove the `f(x)` buttons, this can lead to inconsistent behavior when interacting with presets, which always involve working with relative dates.

I offered @St1ggy several options:
- use the [RelativeRangeDatePickerDialog](https://github.com/gravity-ui/rfc/issues/17#issuecomment-2304849460) component. This way you can draw your trigger, however, the `f(x)` buttons will remain in place
- use the trigger, `Popup` and two `DatePicker` components to select the beginning and end of the range. This case will cover the @St1ggy case. In this case, you will have to make a [hack](https://github.com/gravity-ui/date-components/blob/main/src/components/RelativeRangeDatePicker/components/PickerDialog/PickerDialog.scss#L31-L32) in styles. But it won't be needed when we do [this task](https://github.com/gravity-ui/uikit/issues/1877).

In view of the above, the proposed revision does not look architecturally correct, given that it is possible to complete the task using existing components. I suggest closing the current feature request.
