### ISSUE TITLE
TextInput: render `endContent` exactly in the end of the control

### ISSUE THREAD

**Issue by korvin89** [gravity-ui/rfc#20]
## Objective

`TextInput` locate `endContent` between cross and error elements. It looks a little bit confusing because:
- cross and error elements are dynamically rendered and it makes static `endContent` be dynamic too
- name of property supposes that content should be rendered exactly in the end of the control

<details>
<summary>Example</summary>

![image](https://github.com/user-attachments/assets/128a9501-2dab-44fa-94eb-10212eb233a8)

</details>

## Solution Proposal

I suggest to add a new temporal property `unstable_endContent`:
- this property will be render content after cross and error elements
- this property will be added in the current 6 major
- this property will be renamed to `endContent` in the next major
- old property `endContent` will be removed in the next major

**Comment by raphaello99** [comment]
Hey guys. This change is fine on the design side.

**Comment by Romanycheva** [comment]
This change is fine on the design side
