### ISSUE TITLE
Auto fit mode for Tabs component

### ISSUE THREAD

**Issue by Kabir-Ivan** [gravity-ui/rfc#24]
## Objective

Improve the Tabs component by ensuring all tabs may fit within a single line, addressing issues with overflow when numerous tabs are present.

## Proposed Solution

Introduce an "Auto-Fit" mode for the Tabs component. In this mode, any tabs that cannot fit on a single line will be grouped under a single "Others" tab. This "Others" tab will function as a dropdown menu. When a user selects a tab from the dropdown, the "Others" label will dynamically change to display the name of the selected tab.

## Definition of Done

- Implement the "Auto-Fit" mode for the Tabs component.
- All overflow tabs are collapsed into a single dropdown in the "Others" tab.
- Allow the "Others" label to update dynamically to reflect the currently selected tab from the dropdown.

**Comment by SeqviriouM** [comment]
@sofiushko @amje @korvin89  what do you think?

**Comment by ykamendrovskiy** [comment]
reminds me of `AdaptiveTabs`. https://preview.gravity-ui.com/components/?path=/story/components-adaptivetabs--default

**Comment by korvin89** [comment]
> @sofiushko @amje @korvin89 what do you think?

@SeqviriouM We are on our way to merge this components https://github.com/gravity-ui/rfc/issues/16

**Comment by SeqviriouM** [comment]
@korvin89 can we close then this task in favor of this #16?

**Comment by korvin89** [comment]
> @korvin89 can we close then this task in favor of this #16?

@SeqviriouM yep

**Comment by SeqviriouM** [comment]
@Kabir-Ivan we will solve this issue in #16
