### ISSUE TITLE
Some bugs and improvements for the rangedatepicker component

### ISSUE THREAD

**Issue by dzekh** [gravity-ui/rfc#4]
### Query hint
There are some errors in the tooltip:
instead of a dash with spaces (now — 5m) there should be minuses or hyphens without spaces (now-5m),
This week and Previous month have the same From and To values, and it looks like an error
<img width="1022" alt="image" src="https://github.com/gravity-ui/rfc/assets/26383080/a5ed5df4-8058-4162-a65e-ce3cd4f38cbb">

### Error message
The error message for an incorrect request does not contain clear information on where to look for the “special format” specification.
<img width="624" alt="image" src="https://github.com/gravity-ui/rfc/assets/26383080/36dd7446-9e16-4023-8794-db37837d161c">

### The periods like now/w — now/w
If you set the values now/w for the From and To fields, you may see strange results:
in the hover tooltip the result seems to be adequate but in the callback both dates are the same.
<img width="625" alt="image" src="https://github.com/gravity-ui/rfc/assets/26383080/a97ffed1-d1c0-40df-b165-4252b1ffbd78">

### Full list of possible options
The logic of the query language is not clear and we do not know what other values can be used: is it possible to set intervals for the year, quarter, second, etc. It would be nice to add a link to more detailed query language instructions, or just a complete list.
<img width="667" alt="image" src="https://github.com/gravity-ui/rfc/assets/26383080/7a21f06b-1a2b-4e07-8d94-237cbdd72989">

### Error in a storybook 
An error appears on the custom-presets page in the storybook,  when you choose an interval in picker:
![image](https://github.com/gravity-ui/rfc/assets/26383080/3256ab46-2067-49c1-a451-aa25fbf723b9)

### Tooltip formatting and position
<img width="660" alt="image" src="https://github.com/gravity-ui/rfc/assets/26383080/95df9c2a-9bfc-4762-8540-909a14852070">

### Turning off tabs
The need for tabs for different presets is not always necessary; you would like to be able to turn them off, but now there is no such option.

In this case, you need to leave the opportunity to get a hint on the format for entering relative dates. We suggest moving the tooltip icon to the button level.

Presets without tabs:
<img width="521" alt="image" src="https://github.com/gravity-ui/rfc/assets/26383080/8a977d3f-9bbc-442b-80bd-ed78ca1bb4e8">

### Icon design and layout
The calendar icon itself and its position are different in the Figma library and in the React library
<img width="410" alt="image" src="https://github.com/gravity-ui/rfc/assets/26383080/79685f2e-a74c-4484-9f3f-4426c4532b25">

### “From;” is cut off after changing font
It would be nice to make sure that the width for the **From:** and **To:** text is not hard-coded and depends on the chosen font and boldness, so that the text is always visible.
<img width="381" alt="image" src="https://github.com/gravity-ui/rfc/assets/26383080/4e095b56-36cf-4796-82b0-3068ecfea755">

**Comment by EgorKluch** [comment]
Answer for new [RelativeRangeDatePicker](https://github.com/gravity-ui/date-components/pull/29) component
1. Query hint is fixed
2. Error message doesn't visible for invalid input, only error border.
<img width="448" alt="Screenshot 2024-01-30 at 15 55 25" src="https://github.com/gravity-ui/rfc/assets/2197074/840008b1-fe6e-4e09-aaf0-12551e13ccc1">

3. You can see special format in the hint.
4. The periods like now/w — now/w: This behaviour will be fixed. The end date should be round up.
5. Documentation of full list of possible options. It make sense.
6. Error in a storybook. It isn't actual now.
7. Turning off tabs. Empty preset tabs hides now. Single tab doesn't visible now. But, maybe, it's make sense to move the hint  icon.
8. Icon design and layout. It isn't actual now.
9. “From;” is cut off after changing font. It's make sense. Now label width is hardcoded, but isn't cutted.

**Comment by sareyu** [comment]
@korvin89 take a look, plz

**Comment by resure** [comment]
@korvin89 can you please remind us what is the current status of this issue? Is discussiojn discussion is still in progress?

**Comment by korvin89** [comment]
@resure  There were some changes since our last discussion:
- we've released [this component](https://preview.gravity-ui.com/date-components/?path=/story/components-relativerangedatepicker--default) in date-components lib
- we've fixed `Query hint` issue
- we've added documentation about queries, you can check it [here](https://gravity-ui.com/components/date-components/relative-date-field#valid-input-rules)
- we've fixed `Icon design and layout` issue
- we've fixed label's cutting issue

What should we think about:
- there is not a convenient UX in tooltip part, we think that tooltip should not be a part of component at all
- there is no error message managing yet
- there is no documentation link in error messages related to invalid related date input

**Comment by SeqviriouM** [comment]
@korvin89 can you describe the current status? Is this issue still relevant or should it be put on hold?

**Comment by korvin89** [comment]
> @korvin89 can you describe the current status? Is this issue still relevant or should it be put on hold?

@SeqviriouM we have fixed the main parts of these issues. Currently, work is underway on the design of the hint with syntax and the abandonment of tabs. I think we can leave this issue as it is for now

**Comment by SeqviriouM** [comment]
@korvin89 is this issue still relevant?

**Comment by korvin89** [comment]
> @korvin89 is this issue still relevant?

Nope, we can close it as resolved
