### ISSUE TITLE
Add native input validation to TextInput

### ISSUE THREAD

**Issue by DaniilDem** [gravity-ui/rfc#5]
## Objective

Sometimes it is necessary to validate the input for the TextInput using the [pattern](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/pattern) or attributes for  type=number such as [step, min, max](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number)

## Solution Proposal

There are two options:
1. Add a limited number of attributes to TextInput, such as pattern, step, min, and max
2. Add extra properties to Text Input. 

## Definition of done
In TextInput, you can use browser-side validation/parsing
As example: 
`<TextInput
                                    type="number"
                                    pattern="\d{4,4}"
                                    step=""
                                    step="2"
                                    min="0"
                                    max="9999"
                                />`

**Comment by SeqviriouM** [comment]
@amje @korvin89 what do you think?

**Comment by korvin89** [comment]
@DaniilDem @SeqviriouM Hi! There is no need to add this properties. You already can do this via [controlProps](https://github.com/gravity-ui/uikit/blob/1f2c718faa298795a581c1f1841f2253ade209a6/src/components/controls/TextInput/TextInput.tsx#L36)
