### ISSUE TITLE
Change behaviour of home/end in List

### ISSUE THREAD

**Issue by burashka** [gravity-ui/rfc#9]
## Objective

What is the problem and why is it important?

Keys home/end select first and last item in list. However, users expect change position of cursor in input.

May be, it's difference between MacOS and another system, because ctrl-arrow change position.

## Solution Proposal

What should be done and how?

Сhange behaviour of home/end in List for non-macos users:
- home/end will change position of cursor in input
- ctrl-home/ctrl-end will select first and last item in list

May be, for all users?

## Definition of done

What criteria should be met to consider the task complete?

List provides expected behaviour for home/end keys.

**Comment by resure** [comment]
@korvin89 @amje you might be interested

**Comment by korvin89** [comment]
@resure  We have already released [new list component](https://preview.gravity-ui.com/uikit/?path=/docs/unstable-uselist--docs) and don't have any plans for new features in old list.

**Comment by resure** [comment]
> @resure We have already released [new list component](https://preview.gravity-ui.com/uikit/?path=/docs/unstable-uselist--docs) and don't have any plans for new features in old list.

Well, what matters is not only the fact that a new component was released, but also the speed of adoption of that new component. If new List will be integrated into services as slowly as new calendar (1 to 3 years) then probably old List should be upgraded too so users won't suffer in the meanwhile.

**Comment by ogonkov** [comment]
If focus inside list items Home/End should focus first/last item in list

**Comment by burashka** [comment]
> @resure We have already released [new list component](https://preview.gravity-ui.com/uikit/?path=/docs/unstable-uselist--docs) and don't have any plans for new features in old list.

I see unstable branch in storybook. Can I use it now? When will new list component become stable and publish?

**Comment by korvin89** [comment]
@burashka 
> home/end will change position of cursor in input

Yep, it is completely true according to [w3c Combobox Pattern](https://www.w3.org/WAI/ARIA/apg/patterns/combobox/)

> ctrl-home/ctrl-end will select first and last item in list

There is no such keys behaviour pattern in w3c or or wherever, so our users will not be able to find out about such functionality in any way. I think we should not use patterns that are not standard.

Here my suggestion about your issue https://github.com/gravity-ui/uikit/pull/1491.

**Comment by korvin89** [comment]
@burashka

> I see unstable branch in storybook. Can I use it now? When will new list component become stable and publish?

Yep, you can already use it, but component could have breaking changes in minors cause of in unstable status.

**Comment by amje** [comment]
@burashka @korvin89  I can see that feature is shipped to the current `List`, can we close this issue?
